USE zdrobix;
GO

CREATE TABLE CLIENTI (
	id INT PRIMARY KEY IDENTITY,
	nume VARCHAR(40),
	varsta INT
)

CREATE TABLE GRADE_SEVERITATE (
	id INT PRIMARY KEY IDENTITY,
	grad VARCHAR(40)
)

CREATE TABLE CAUZE (
	id INT PRIMARY KEY IDENTITY,
	cauza VARCHAR(40)
)

CREATE TABLE BOLI (
	id INT PRIMARY KEY IDENTITY,
	nume VARCHAR(40),
	id_grad_severitate INT FOREIGN KEY REFERENCES GRADE_SEVERITATE(id),
	id_cauza INT FOREIGN KEY REFERENCES CAUZE(id)
)

CREATE TABLE BENEFICII (
	id INT PRIMARY KEY IDENTITY,
	nume VARCHAR(40)
)

CREATE TABLE TARI (
	id INT PRIMARY KEY IDENTITY,
	nume VARCHAR(40)
)

CREATE TABLE PRODUCATORI (
	id INT PRIMARY KEY IDENTITY,
	nume VARCHAR(40),
	id_tara INT FOREIGN KEY REFERENCES TARI(id)
)

CREATE TABLE MEDICAMENTE (
	id INT PRIMARY KEY IDENTITY,
	nume VARCHAR(40),
	pret INT,
	id_producator INT FOREIGN KEY REFERENCES PRODUCATORI(id)
)

CREATE TABLE TRANZACTII (
	id INT PRIMARY KEY IDENTITY,
	id_client INT FOREIGN KEY REFERENCES CLIENTI(id),
	id_medicamente INT FOREIGN KEY REFERENCES MEDICAMENTE(id),
	data_tranzactie DATE
)

CREATE TABLE BENEFICII_MEDICAMENTE (
	id INT PRIMARY KEY IDENTITY,
	id_medicament INT FOREIGN KEY REFERENCES MEDICAMENTE(id),
	id_beneficiu INT FOREIGN KEY REFERENCES BENEFICII(id)
)

CREATE TABLE BOLI_CLIENTI (
	id INT PRIMARY KEY IDENTITY,
	id_client INT FOREIGN KEY REFERENCES CLIENTI(id),
	id_boala INT FOREIGN KEY REFERENCES BOLI(id),
	data_diagnostic DATE
)

DROP TABLE BENEFICII;
DROP TABLE BENEFICII_MEDICAMENTE;
DROP TABLE CLIENTI;
DROP TABLE GRADE_SEVERITATE;
DROP TABLE BOLI;
DROP TABLE BOLI_CLIENTI;
DROP TABLE TRANZACTII;
DROP TABLE MEDICAMENTE;